"""initial tables

Revision ID: 06a3b5a78377
Revises: 
Create Date: 2025-11-15 20:05:21.056733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06a3b5a78377'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_category_name'), 'tb_category', ['name'], unique=True)
    op.create_table('tb_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_provider_contact_email'), 'tb_provider', ['contact_email'], unique=True)
    op.create_index(op.f('ix_tb_provider_name'), 'tb_provider', ['name'], unique=True)
    op.create_table('tb_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tb_category.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['tb_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_product_name'), 'tb_product', ['name'], unique=True)
    op.create_table('tb_stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tb_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_stock_movement')
    op.drop_index(op.f('ix_tb_product_name'), table_name='tb_product')
    op.drop_table('tb_product')
    op.drop_index(op.f('ix_tb_provider_name'), table_name='tb_provider')
    op.drop_index(op.f('ix_tb_provider_contact_email'), table_name='tb_provider')
    op.drop_table('tb_provider')
    op.drop_index(op.f('ix_tb_category_name'), table_name='tb_category')
    op.drop_table('tb_category')
    # ### end Alembic commands ###
