from typing import Optional
from pydantic import BaseModel, Field

class CategoryBase(BaseModel):
    """
    Shared attributes between all Category DTO schemas.
    """
    name: str = Field(
        ...,
        min_length=2,
        max_length=80,
        description="Unique name identifying the category."
    )


class CategoryCreate(CategoryBase):
    """
    Payload required to CREATE a new Category.
    No id attribute because it is generated by the database.
    """
    pass


class CategoryUpdate(BaseModel):
    """
    Payload allowed to UPDATE a Category.
    All fields optional because it's a partial update.
    """
    name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=80,
        description="Updated unique name for the category."
    )


class CategoryRead(CategoryBase):
    """
    Schema used for returning Category data in responses.
    API responses should use this instead of DB models.
    """
    id: int = Field(..., description="Database primary key.")

    model_config = {
        "from_attributes": True
    }