from typing import Optional, List
from pydantic import BaseModel, Field
from inventory_management.schemas.category import CategoryRead
from inventory_management.schemas.provider import ProviderRead
from inventory_management.schemas.stock_movement import StockMovementRead

class ProductBase(BaseModel):
    """
    Shared attributes between all Product DTO schemas.
    """
    name: str = Field(
        ..., 
        min_length=2, 
        max_length=80, 
        description="Human-readable name of the product."
    )
    category_id: int = Field(..., gt=0, description="Foreign key to the product category.")
    provider_id: Optional[int] = Field(
        default=None, 
        gt=0, 
        description="Foreign key to the product provider."
    )


class ProductCreate(ProductBase):
    """
    Payload required to CREATE a new Product.
    No id attribute because it is generated by the database.
    """
    pass


class ProductUpdate(BaseModel):
    """
    Payload allowed to UPDATE a Product.
    All fields optional because it's a partial update.
    """
    name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=80,
    )
    category_id: Optional[int] = Field(gt=0)
    provider_id: Optional[int] = Field(gt=0)


class ProductRead(ProductBase):
    """
    Schema used for returning Product data in responses.
    API responses should use this instead of DB models.
    """
    id: int = Field(..., description="Database primary key.")

    model_config = {
        "from_attributes": True
    }


class ProductReadDetailed(BaseModel):
    id: int = Field(..., description="Database primary key.")

    name: str = Field(
        ..., 
        min_length=2, 
        max_length=80, 
        description="Human-readable name of the product."
    )

    category: CategoryRead
    provider: Optional[ProviderRead]
    stock_movements: List[StockMovementRead] = []