from typing import Optional
from pydantic import BaseModel, Field, EmailStr


class ProviderBase(BaseModel):
    """
    Shared attributes between all Provider DTO schemas.
    """
    name: str = Field(
        ...,
        min_length=2,
        max_length=80,
        description="Unique name identifying the provider."
    )
    contact_email: EmailStr = Field(
        ...,
        min_length=5,
        max_length=80
    )


class ProviderCreate(ProviderBase):
    """
    Payload required to CREATE a new Provider.
    No id attribute because it is generated by the database.
    """
    pass


class ProviderUpdate(BaseModel):
    """
    Payload allowed to UPDATE a Provider.
    All fields optional because it's a partial update.
    """
    name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=80,
        description="Updated unique name for the provider."
    )
    contact_email: Optional[EmailStr] = Field(
        default=None,
        min_length=5,
        max_length=80
    )


class ProviderRead(ProviderBase):
    """
    Schema used for returning Category data in responses.
    API responses should use this instead of DB models.
    """
    id: int = Field(..., description="Database primary key.")

    model_config = {
        "from_attributes": True
    }