from typing import Optional
from pydantic import BaseModel, Field
from inventory_management.models.stock_movements import MovementType
from datetime import datetime


class StockMovementBase(BaseModel):
    """
    Shared attributes between all StockMovement DTO schemas.
    """
    product_id: int = Field(
        ...,
        gt=0,
        description="Foreign key referencing the product whose stock is modified."
    )
    movement_type: MovementType = Field(
        ...,
        description="Type of stock movement: IN adds stock, OUT subtracts stock."
    )
    quantity: int = Field(
        ...,
        gt=0,
        description="Positive integer amount to adjust the stock with."
    )


class StockMovementCreate(StockMovementBase):
    """
    Payload required to CREATE a new StockMovement.
    No id attribute because it is generated by the database.
    """
    pass


class StockMovementUpdate(BaseModel):
    """
    Payload allowed to UPDATE a StockMovement.
    All fields optional because it's a partial update.
    """
    product_id: Optional[int] = Field(default=None, gt=0)
    quantity: Optional[int] = Field(default=None,gt=0)


class StockMovementRead(StockMovementBase):
    """
    Schema used for returning StockMovement data in responses.
    API responses should use this instead of DB models.
    """
    id: int = Field(..., description="Database primary key.")
    created_at: datetime = Field(
        ...,
        description="Timestamp automatically generated when the movement is recorded."
    )
    
    model_config = {
        "from_attributes": True
    }